# Generated by Django 2.2.9 on 2020-04-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookBusinessManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myshopify_domain', models.CharField(help_text='Shopify store domain.', max_length=100, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('business_id', models.BigIntegerField()),
                ('account_id', models.BigIntegerField()),
                ('pixel', models.BigIntegerField()),
                ('connect', models.BooleanField(default=False, help_text='App facebook connect.')),
                ('access_token', models.TextField(help_text='Permanent token received from facebook.')),
                ('access_token_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField()),
                ('campaign_type', models.CharField(
                    choices=[('new', 'New Audience'), ('rel', 'Relevant Audience'), ('ret', 'Retargeting Audience')],
                    default=('new', 'New Audience'), max_length=3)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='facebook_app.FacebookBusinessManager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.BigIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='facebook_app.FacebookBusinessManager')),
                ('campaign', models.ManyToManyField(to='facebook_app.FacebookCampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
