# Generated by Django 2.2.9 on 2020-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcampaign',
            name='campaign_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookfeed',
            name='feed_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
