# Generated by Django 2.2.9 on 2020-04-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0002_auto_20200413_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaign',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
