# Generated by Django 2.2.9 on 2020-04-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0003_facebookcampaign_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookfeed',
            name='campaign',
        ),
        migrations.AddField(
            model_name='facebookfeed',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='facebook_app.FacebookCampaign'),
        ),
    ]
