# Generated by Django 2.2.9 on 2020-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0004_auto_20200416_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookbusinessmanager',
            name='page',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='adset_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookfeed',
            name='catalog_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookfeed',
            name='product_set_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookbusinessmanager',
            name='account_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookbusinessmanager',
            name='business_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookbusinessmanager',
            name='pixel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookbusinessmanager',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
