# Generated by Django 2.2.9 on 2020-05-05 15:01

import django_mysql.models
from django.db import migrations

import facebook_app.models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0005_auto_20200420_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaign',
            name='data',
            field=django_mysql.models.JSONField(default=facebook_app.models.camp_data),
        ),
    ]
