# Generated by Django 2.2.9 on 2020-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('facebook_app', '0006_facebookcampaign_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaign',
            name='ad_creative_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookcampaign',
            name='ads_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
