# Generated by Django 2.2.9 on 2020-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shopify store name.', max_length=100, null=True)),
                ('myshopify_domain', models.CharField(help_text='Shopify store domain.', max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Store email address.', max_length=100, null=True)),
                ('shop_owner',
                 models.CharField(blank=True, help_text='Shopify store owner name.', max_length=100, null=True)),
                ('country_name', models.CharField(blank=True, help_text='Store location.', max_length=100, null=True)),
                ('access_token', models.CharField(help_text='Permanent token received from shopify.', max_length=100)),
                ('installed', models.BooleanField(blank=True, help_text='App installed.', null=True)),
                ('date_installed', models.DateTimeField(blank=True, help_text='App installation date.', null=True)),
                ('date_paid', models.DateTimeField(blank=True, help_text='App paid date.', null=True)),
                ('date_uninstalled', models.DateTimeField(blank=True, help_text='App uninstalled date.', null=True)),
                ('premium', models.BooleanField(blank=True, help_text='App premium.', null=True)),
            ],
        ),
    ]
