# Generated by Django 2.2.9 on 2020-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='offer_count',
            field=models.IntegerField(default=0, help_text='Count offer.'),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='installed',
            field=models.BooleanField(default=False, help_text='App installed.'),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='premium',
            field=models.BooleanField(default=False, help_text='App premium.'),
        ),
    ]
